language: generic

deploy:
- provider: s3
  access_key_id: $access_key_id
  secret_access_key: $secret_key
  bucket: tex-to-pdf
  local-dir: page
  region: us-east-1
  skip-cleanup: true
  on:
    repo: daniel-craig/tex-to-pdf
